# Generated by Django 2.1.2 on 2018-12-18 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180928_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=32)),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 18, 14, 45, 0, 691706))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
