# Generated by Django 2.1.2 on 2018-12-18 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181218_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetlink',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 18, 14, 0, 9, 504188, tzinfo=utc)),
        ),
    ]
