# Generated by Django 2.1.2 on 2018-12-18 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181218_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetlink',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 18, 14, 3, 30, 538578, tzinfo=utc)),
        ),
    ]
