# Generated by Django 2.1 on 2018-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutriscore', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images/pictures/')),
                ('nutrition', models.ImageField(upload_to='images/nutrition/')),
                ('external_link', models.URLField()),
                ('categories', models.ManyToManyField(related_name='products', to='products.Category')),
            ],
        ),
    ]
