# Generated by Django 2.1 on 2018-09-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product'},
        ),
    ]
