# Generated by Django 2.1 on 2018-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180827_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summation',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
