# Generated by Django 2.1 on 2018-10-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180928_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_link',
        ),
    ]
