# Generated by Django 2.1 on 2018-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180906_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summation',
            field=models.CharField(max_length=300),
        ),
    ]
