# Generated by Django 2.1 on 2018-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180906_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(),
        ),
    ]
